pipeline {
    agent any
    
    environment {
        // REMOVE THIS LINE: JENKINS_DEPLOY_DIR = credentials('jenkins-deploy-dir')
        GITHUB_SSH_CREDENTIAL_ID = 'f2279fbb-b675-4191-bb6e-5e5c0d1421a5'
        DB_PASSWORD = credentials('tms-db-password')
        JWT_KEY = credentials('tms-jwt-key')
        ADMIN_PASSWORD = credentials('tms-admin-password')
        APP_URLS = credentials('tms-app-urls')
    }
    
    stages {
        stage('Checkout from GitHub') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'git@github.com:testing860/TMSDevOps.git',
                        credentialsId: "${GITHUB_SSH_CREDENTIAL_ID}"
                    ]]
                ])
                sh 'echo "Repository checked out to: $(pwd)"'
            }
        }
        
        stage('Build & Test Application') {
            steps {
                sh '''
                    echo "Building .NET solution..."
                    dotnet build --configuration Release
                    echo "Running tests..."
                    dotnet test --configuration Release --logger "trx" || echo "Tests completed"
                '''
            }
        }
        
        stage('Create Secure Environment File') {
            steps {
                sh """
                    cat > .env << 'EOF'
# ===== AUTO-GENERATED BY JENKINS - DO NOT COMMIT =====
# Database Connection
DB_SERVER=localhost
DB_NAME=TaskManagementSystem
DB_USER=sa
DB_PASSWORD=${DB_PASSWORD}

# JWT Settings
JWT_KEY=${JWT_KEY}
JWT_ISSUER=TMSAPI
JWT_AUDIENCE=TMSWebClient

# Admin User for Seeding
ADMIN_EMAIL=admin@tms.com
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_DISPLAYNAME=Admin

# Application Runtime
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=${APP_URLS}
EOF
                    
                    echo "✅ Secure .env file created (secrets masked in logs)"
                """
            }
        }
        
        stage('Publish & Deploy') {
            steps {
                sh """
                    echo "Publishing API..."
                    dotnet publish TMS.API/TMS.API.csproj \\
                        -c Release -o ./publish-api \\
                        --runtime linux-x64
                    
                    echo "Publishing Web (Blazor WASM)..."
                    dotnet publish TMS.Web/TMS.Web.csproj \\
                        -c Release -o ./publish-web \\
                        --runtime linux-x64
                    
                    echo "Deploying to /opt/tms-app/"
                    
                    # Create deployment directories
                    sudo mkdir -p /opt/tms-app/api
                    sudo mkdir -p /opt/tms-app/web
                    
                    # Stop services if they exist
                    sudo systemctl stop tms-api.service 2>/dev/null || true
                    sudo systemctl stop tms-web.service 2>/dev/null || true
                    
                    # Deploy API
                    sudo rm -rf /opt/tms-app/api/*
                    sudo cp -r ./publish-api/* /opt/tms-app/api/
                    sudo cp .env /opt/tms-app/api/
                    
                    # Deploy Web (Blazor WASM static files)
                    sudo rm -rf /opt/tms-app/web/*
                    sudo cp -r ./publish-web/wwwroot/* /opt/tms-app/web/
                    
                    # Fix permissions
                    sudo chown -R ec:ec /opt/tms-app
                    
                    # Create systemd service for API (ONLY if it doesn't exist)
                    if [ ! -f "/etc/systemd/system/tms-api.service" ]; then
                        sudo tee /etc/systemd/system/tms-api.service << 'API_SERVICE'
[Unit]
Description=TMS API Backend
After=network.target

[Service]
WorkingDirectory=/opt/tms-app/api
ExecStart=/usr/bin/dotnet TMS.API.dll
EnvironmentFile=/opt/tms-app/api/.env
Restart=always
RestartSec=10
User=ec
Group=ec
SyslogIdentifier=tms-api
Environment=ASPNETCORE_ENVIRONMENT=Production

[Install]
WantedBy=multi-user.target
API_SERVICE
                    fi
                    
                    # Create systemd service for Web (simple HTTP server on port 7130)
                    if [ ! -f "/etc/systemd/system/tms-web.service" ]; then
                        sudo tee /etc/systemd/system/tms-web.service << 'WEB_SERVICE'
[Unit]
Description=TMS Web Frontend (Static Blazor)
After=network.target

[Service]
WorkingDirectory=/opt/tms-app/web
# Simple HTTP server for static files on port 7130
ExecStart=/usr/bin/python3 -m http.server 7130
Restart=always
RestartSec=10
User=ec
Group=ec
SyslogIdentifier=tms-web

[Install]
WantedBy=multi-user.target
WEB_SERVICE
                    fi
                    
                    # Reload and start services
                    sudo systemctl daemon-reload
                    sudo systemctl enable tms-api.service tms-web.service
                    sudo systemctl start tms-api.service tms-web.service
                    
                    echo "🚀 Deployment complete!"
                    echo "API running at: ${APP_URLS}"
                    echo "Web running at: http://$(hostname -I | awk '{print \$1}'):7130"
                """
            }
        }
    }
    
    post {
        success {
            echo '🎉 Pipeline succeeded!'
            sh 'echo "Application deployed and running successfully."'
        }
        failure {
            echo '❌ Pipeline failed. Check logs above.'
        }
    }
}
