pipeline {
    agent any
    
    environment {
        JENKINS_WORKSPACE = credentials('jenkins-custom-workspace')
        JENKINS_DEPLOY_DIR = credentials('jenkins-deploy-dir')
        GITHUB_REPO_URL = credentials('github-repo-url')
        GITHUB_SSH_CREDENTIAL_ID = 'f2279fbb-b675-4191-bb6e-5e5c0d1421a5'
        DB_PASSWORD = credentials('tms-db-password')
        JWT_KEY = credentials('tms-jwt-key')
        ADMIN_PASSWORD = credentials('tms-admin-password')
        APP_URLS = credentials('tms-app-urls')
    }
    
    stages {
        stage('Checkout from GitHub') {
            steps {
                dir("${JENKINS_WORKSPACE}") {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[
                            url: "${GITHUB_REPO_URL}",
                            credentialsId: "${GITHUB_SSH_CREDENTIAL_ID}"
                        ]]
                    ])
                    sh 'echo "Repository checked out to: $(pwd)"'
                }
            }
        }
        
        stage('Build & Test Application') {
            steps {
                dir("${JENKINS_WORKSPACE}") {
                    sh '''
                        echo "Building .NET solution..."
                        dotnet build --configuration Release
                        echo "Running tests..."
                        dotnet test --configuration Release --logger "trx" || echo "Tests completed"
                    '''
                }
            }
        }
        
        stage('Create Secure Environment File') {
            steps {
                dir("${JENKINS_WORKSPACE}") {
                    // FIXED: Use double quotes for the heredoc to allow variable expansion
                    sh """
                        cat > .env << 'EOF'
# ===== AUTO-GENERATED BY JENKINS - DO NOT COMMIT =====
# Database Connection
DB_SERVER=localhost
DB_NAME=TaskManagementSystem
DB_USER=sa
DB_PASSWORD=${DB_PASSWORD}

# JWT Settings
JWT_KEY=${JWT_KEY}
JWT_ISSUER=TMSAPI
JWT_AUDIENCE=TMSWebClient

# Admin User for Seeding
ADMIN_EMAIL=admin@tms.com
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_DISPLAYNAME=Admin

# Application Runtime
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=${APP_URLS}
EOF
                        
                        echo "✅ Secure .env file created (secrets masked in logs)"
                    """
                }
            }
        }
        
        stage('Publish & Deploy') {
            steps {
                dir("${JENKINS_WORKSPACE}") {
                    sh """
                        echo "Publishing application..."
                        dotnet publish TMS.API/TMS.API.csproj \\
                            -c Release -o ./publish \\
                            --runtime linux-x64
                        
                        echo "Deploying to: ${JENKINS_DEPLOY_DIR}"
                        sudo systemctl stop tms-app.service 2>/dev/null || true
                        sudo rm -rf ${JENKINS_DEPLOY_DIR}/*
                        sudo cp -r ./publish/* ${JENKINS_DEPLOY_DIR}/
                        sudo cp .env ${JENKINS_DEPLOY_DIR}/
                        
                        # Fix permissions - adjust user as needed
                        sudo chown -R ec:ec ${JENKINS_DEPLOY_DIR} || sudo chown -R jenkins:jenkins ${JENKINS_DEPLOY_DIR}
                        
                        sudo systemctl start tms-app.service
                        
                        echo "🚀 Deployment complete!"
                        echo "Application running at: ${APP_URLS}"
                    """
                }
            }
        }
    }
    
    post {
        success {
            echo '🎉 Pipeline succeeded!'
            sh 'echo "Application deployed and running successfully."'
        }
        failure {
            echo '❌ Pipeline failed. Check logs above.'
        }
    }
}
