pipeline {
    agent any
    
    environment {
        GITHUB_SSH_CREDENTIAL_ID = 'f2279fbb-b675-4191-bb6e-5e5c0d1421a5'
        DB_PASSWORD = credentials('tms-db-password')
        JWT_KEY = credentials('tms-jwt-key')
        ADMIN_PASSWORD = credentials('tms-admin-password')
        APP_URLS = credentials('tms-app-urls')
    }
    
    stages {
        stage('Checkout from GitHub') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'git@github.com:testing860/TMSDevOps.git',
                        credentialsId: "${GITHUB_SSH_CREDENTIAL_ID}"
                    ]]
                ])
                sh 'echo "Repository checked out to: $(pwd)"'
            }
        }
        
        stage('Build & Test Application') {
            steps {
                sh '''
                    echo "Building .NET solution..."
                    dotnet build --configuration Release
                    echo "Running tests..."
                    dotnet test --configuration Release --logger "trx" || echo "Tests completed"
                '''
            }
        }
        
        stage('Create Secure Environment File') {
            steps {
                sh """
                    cat > .env << 'EOF'
# ===== AUTO-GENERATED BY JENKINS - DO NOT COMMIT =====
# Database Connection
DB_SERVER=localhost
DB_NAME=TaskManagementSystem
DB_USER=sa
DB_PASSWORD=${DB_PASSWORD}

# JWT Settings
JWT_KEY=${JWT_KEY}
JWT_ISSUER=TMSAPI
JWT_AUDIENCE=TMSWebClient

# Admin User for Seeding
ADMIN_EMAIL=admin@tms.com
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_DISPLAYNAME=Admin

# Application Runtime
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=${APP_URLS}
EOF
                    
                    echo "✅ Secure .env file created (secrets masked in logs)"
                """
            }
        }
        
        stage('Publish & Deploy') {
            steps {
                sh """
                    echo "Publishing API..."
                    dotnet publish TMS.API/TMS.API.csproj \\
                        -c Release -o ./publish-api \\
                        --runtime linux-x64
                    
                    echo "Publishing Web (Blazor WASM)..."
                    dotnet publish TMS.Web/TMS.Web.csproj \\
                        -c Release -o ./publish-web \\
                        --runtime linux-x64
                    
                    echo "Deploying to /opt/tms-app/"
                    
                    # Create deployment directories
                    sudo mkdir -p /opt/tms-app/api
                    sudo mkdir -p /opt/tms-app/web
                    
                    # Stop services if they exist
                    sudo systemctl stop tms-api.service 2>/dev/null || true
                    
                    # Deploy API
                    sudo rm -rf /opt/tms-app/api/*
                    sudo cp -r ./publish-api/* /opt/tms-app/api/
                    sudo cp .env /opt/tms-app/api/
                    
                    # Deploy Web (Blazor WASM static files)
                    sudo rm -rf /opt/tms-app/web/*
                    sudo cp -r ./publish-web/wwwroot/* /opt/tms-app/web/
                    
                    # Fix permissions
                    sudo chown -R ec:ec /opt/tms-app
                    
                    # Create systemd service for API (ONLY if it doesn't exist)
                    if [ ! -f "/etc/systemd/system/tms-api.service" ]; then
                        sudo tee /etc/systemd/system/tms-api.service << 'API_SERVICE'
[Unit]
Description=TMS API Backend
After=network.target

[Service]
WorkingDirectory=/opt/tms-app/api
ExecStart=/usr/bin/dotnet TMS.API.dll
EnvironmentFile=/opt/tms-app/api/.env
Restart=always
RestartSec=10
User=ec
Group=ec
SyslogIdentifier=tms-api
Environment=ASPNETCORE_ENVIRONMENT=Production

[Install]
WantedBy=multi-user.target
API_SERVICE
                    fi
                    
                    # Install nginx if not installed
                    if ! command -v nginx &> /dev/null; then
                        echo "Installing nginx..."
                        sudo apt-get update
                        sudo apt-get install -y nginx
                    fi
                    
                    # Configure nginx for Blazor WebAssembly on port 7130
                    echo "Configuring nginx for Blazor WebAssembly..."
                    sudo tee /etc/nginx/sites-available/tms << 'NGINX_CONFIG'
server {
    listen 7130;
    server_name _;
    
    # Root directory for Blazor static files
    root /opt/tms-app/web;
    
    # Serve index.html for all routes (SPA support)
    location / {
        try_files \\\$uri \\\$uri/ /index.html;
        index index.html;
    }
    
    # Cache static assets
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    
    # Proxy API requests to the .NET API
    location /api {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \\\$http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host \\\$host;
        proxy_cache_bypass \\\$http_upgrade;
        proxy_set_header X-Forwarded-For \\\$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \\\$scheme;
        proxy_set_header X-Real-IP \\\$remote_addr;
        
        # Increase timeout for API calls
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # Proxy WebSocket for SignalR/real-time features if needed
    location /hubs {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \\\$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \\\$host;
    }
    
    # Health check endpoint
    location /health {
        proxy_pass http://localhost:5000/health;
        proxy_http_version 1.1;
        proxy_set_header Host \\\$host;
        access_log off;
    }
}
NGINX_CONFIG
                    
                    # Enable the site and disable default
                    sudo ln -sf /etc/nginx/sites-available/tms /etc/nginx/sites-enabled/
                    sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
                    
                    # Test nginx configuration
                    sudo nginx -t
                    
                    # Restart nginx
                    sudo systemctl restart nginx
                    
                    # Reload and start API service
                    sudo systemctl daemon-reload
                    sudo systemctl enable tms-api.service
                    sudo systemctl start tms-api.service
                    
                    # Allow port 7130 in firewall
                    sudo ufw allow 7130/tcp 2>/dev/null || true
                    
                    # Wait a moment for services to start
                    sleep 5
                    
                    # Test services
                    echo "Testing API..."
                    API_STATUS=\$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health || echo "failed")
                    echo "API health check: \${API_STATUS}"
                    
                    echo "Testing Web via nginx..."
                    WEB_STATUS=\$(curl -s -o /dev/null -w "%{http_code}" http://localhost:7130/ || echo "failed")
                    echo "Web access: \${WEB_STATUS}"
                    
                    echo "🚀 Deployment complete!"
                    echo "API running at: \${APP_URLS}"
                    echo "Web (Blazor) served by nginx on port 7130"
                    echo "Access your app at: http://\$(hostname -I | awk '{print \\\$1}'):7130"
                    echo "API is available at: http://\$(hostname -I | awk '{print \\\$1}'):5000"
                    echo "API proxy: http://\$(hostname -I | awk '{print \\\$1}'):7130/api"
                """
            }
        }
    }
    
    post {
        success {
            echo '🎉 Pipeline succeeded!'
            sh 'echo "Application deployed and running successfully."'
        }
        failure {
            echo '❌ Pipeline failed. Check logs above.'
        }
    }
}
